#!/usr/bin/env python3
"""
SuenWeb Extension Packer (Python fallback)
Builds:
  - public/extension/suenweb.crx & extension/suenweb.crx (Chrome CRX3 format)
  - public/extension/suenweb-firefox.xpi & extension/suenweb-firefox.xpi (Firefox XPI)
  - public/extension/suenweb-extension-chrome.zip
  - public/extension/suenweb-extension-firefox.zip
  - src/extensions.ts (Cloudflare Workers embedded assets)
"""
import os, sys, json, base64, struct, hashlib, subprocess, zipfile, io

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

def read_text(rel):
    with open(os.path.join(ROOT, rel), 'r', encoding='utf-8') as fp:
        return fp.read()

def read_bytes(rel):
    with open(os.path.join(ROOT, rel), 'rb') as fp:
        return fp.read()

manifest_chrome = read_text('extension/manifest.json')
manifest_firefox = read_text('extension/manifest_firefox.json')
background_js = read_text('extension/background.js')
popup_html = read_text('extension/popup.html')
popup_js = read_text('extension/popup.js')
icon_svg = read_text('extension/icons/icon.svg')
icon_16 = read_bytes('extension/icons/icon-16.png')
icon_48 = read_bytes('extension/icons/icon-48.png')
icon_128 = read_bytes('extension/icons/icon-128.png')

# 1. Build Chrome Zip
buf_chrome = io.BytesIO()
with zipfile.ZipFile(buf_chrome, 'w', zipfile.ZIP_DEFLATED) as zf:
    zf.writestr('manifest.json', manifest_chrome)
    zf.writestr('background.js', background_js)
    zf.writestr('popup.html', popup_html)
    zf.writestr('popup.js', popup_js)
    zf.writestr('icons/icon-16.png', icon_16)
    zf.writestr('icons/icon-48.png', icon_48)
    zf.writestr('icons/icon-128.png', icon_128)
    zf.writestr('icons/icon.svg', icon_svg)
chrome_zip = buf_chrome.getvalue()

# 2. Build Firefox Zip
buf_firefox = io.BytesIO()
with zipfile.ZipFile(buf_firefox, 'w', zipfile.ZIP_DEFLATED) as zf:
    zf.writestr('manifest.json', manifest_firefox)
    zf.writestr('background.js', background_js)
    zf.writestr('popup.html', popup_html)
    zf.writestr('popup.js', popup_js)
    zf.writestr('icons/icon-16.png', icon_16)
    zf.writestr('icons/icon-48.png', icon_48)
    zf.writestr('icons/icon-128.png', icon_128)
    zf.writestr('icons/icon.svg', icon_svg)
firefox_zip = buf_firefox.getvalue()

# 3. Ensure Key
key_file = os.path.join(ROOT, 'extension/key.pem')
if not os.path.exists(key_file):
    subprocess.run(['openssl', 'genrsa', '-out', key_file, '2048'], check=True)

der_pub = subprocess.check_output(['openssl', 'rsa', '-in', key_file, '-pubout', '-outform', 'DER'])

# 4. Pack CRX3
def encode_varint(n):
    res = bytearray()
    while n > 0x7f:
        res.append((n & 0x7f) | 0x80)
        n >>= 7
    res.append(n & 0x7f)
    return bytes(res)

def pb_field(tag, wire_type, data):
    key = encode_varint((tag << 3) | wire_type)
    if wire_type == 2:
        return key + encode_varint(len(data)) + data
    return key + data

crx_id = hashlib.sha256(der_pub).digest()[:16]
signed_header_data = pb_field(10000, 2, pb_field(10000, 2, crx_id))

to_sign = b'CRX3 SignedData\x00' + struct.pack('<I', len(signed_header_data)) + signed_header_data + chrome_zip

p = subprocess.Popen(['openssl', 'dgst', '-sha256', '-sign', key_file], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
sig, _ = p.communicate(input=to_sign)

key_proof = pb_field(1, 2, der_pub) + pb_field(2, 2, sig)
crx_header = pb_field(2, 2, key_proof) + pb_field(10000, 2, signed_header_data)

crx_data = b'Cr24' + struct.pack('<I', 3) + struct.pack('<I', len(crx_header)) + crx_header + chrome_zip

ext_id = ''.join(chr(ord('a') + ((b >> 4) & 0x0f)) + chr(ord('a') + (b & 0x0f)) for b in crx_id)

# 5. Output files
public_ext = os.path.join(ROOT, 'public/extension')
ext_dir = os.path.join(ROOT, 'extension')
os.makedirs(public_ext, exist_ok=True)

with open(os.path.join(public_ext, 'suenweb.crx'), 'wb') as fp: fp.write(crx_data)
with open(os.path.join(ext_dir, 'suenweb.crx'), 'wb') as fp: fp.write(crx_data)

with open(os.path.join(public_ext, 'suenweb-firefox.xpi'), 'wb') as fp: fp.write(firefox_zip)
with open(os.path.join(ext_dir, 'suenweb-firefox.xpi'), 'wb') as fp: fp.write(firefox_zip)

with open(os.path.join(public_ext, 'suenweb-extension-chrome.zip'), 'wb') as fp: fp.write(chrome_zip)
with open(os.path.join(public_ext, 'suenweb-extension-firefox.zip'), 'wb') as fp: fp.write(firefox_zip)

print(f'✅ Packaged suenweb.crx ({len(crx_data)/1024:.1f} KB) - Extension ID: {ext_id}')
print(f'✅ Packaged suenweb-firefox.xpi ({len(firefox_zip)/1024:.1f} KB)')

# 6. Regenerate src/extensions.ts
lit = lambda s: json.dumps(s)
out_ts = f'''// AUTO-GENERATED by scripts/pack-extension.mjs — do not edit by hand.
// Edit the source files under extension/ then run: node scripts/pack-extension.mjs
import {{ zipSync, strToU8 }} from 'fflate';

const MANIFEST_CHROME = {lit(manifest_chrome)};
const MANIFEST_FIREFOX = {lit(manifest_firefox)};
const BACKGROUND_JS = {lit(background_js)};
const POPUP_HTML = {lit(popup_html)};
const POPUP_JS = {lit(popup_js)};
const ICON_SVG = {lit(icon_svg)};
const ICON_16_B64 = {lit(base64.b64encode(icon_16).decode('utf-8'))};
const ICON_48_B64 = {lit(base64.b64encode(icon_48).decode('utf-8'))};
const ICON_128_B64 = {lit(base64.b64encode(icon_128).decode('utf-8'))};
const CRX_B64 = {lit(base64.b64encode(crx_data).decode('utf-8'))};
const XPI_B64 = {lit(base64.b64encode(firefox_zip).decode('utf-8'))};

export const EXTENSION_ID = {lit(ext_id)};

function b64ToU8(b64: string): Uint8Array {{
  const bin = atob(b64);
  const u8 = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) {{
    u8[i] = bin.charCodeAt(i);
  }}
  return u8;
}}

export function createExtensionZip(browserType: 'chrome' | 'firefox'): Uint8Array {{
  const manifest = browserType === 'chrome' ? MANIFEST_CHROME : MANIFEST_FIREFOX;

  const files = {{
    'manifest.json': strToU8(manifest),
    'background.js': strToU8(BACKGROUND_JS),
    'popup.html': strToU8(POPUP_HTML),
    'popup.js': strToU8(POPUP_JS),
    'icons/icon-16.png': b64ToU8(ICON_16_B64),
    'icons/icon-48.png': b64ToU8(ICON_48_B64),
    'icons/icon-128.png': b64ToU8(ICON_128_B64),
    'icons/icon.svg': strToU8(ICON_SVG),
  }};

  return zipSync(files);
}}

export function getExtensionCrx(): Uint8Array {{
  return b64ToU8(CRX_B64);
}}

export function getExtensionXpi(): Uint8Array {{
  return b64ToU8(XPI_B64);
}}
'''

with open(os.path.join(ROOT, 'src/extensions.ts'), 'w', encoding='utf-8') as fp:
    fp.write(out_ts)
print('✅ src/extensions.ts regenerated successfully')
